spring:
  application:
    name: basic auth demo
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    jdbcUrl: "jdbc:mysql://localhost:3306/userservice?autoreconnect=true"
    password: "root"
    username: "root"